version: '3.4'
services:
  ####################
  # Backing services #
  ####################
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  ################
  # Our services #
  ################
  web:
    build:
      context: .
      target: vue
    restart: always
    image: nypaddlingproject-web
    command: "yarn serve"
    volumes:
      - ./web/vue.js:/app

  app:
    build:
      context: .
      target: build-server
    hostname: nypaddledev.com
    image: nypaddlingproject
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongo
    volumes:
      # Mount our local codebase over the codebase baked into the image.
      # Restarting the container will run your local code, no need to rebuild.
      - ./pyserver/server.py:/app/server.py
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      BASE_URL: "nypaddledev.com"
      APP_PROTOCOL: "https"
      APP_DOMAIN: nypaddledev.com
      PREFERRED_URL_SCHEME: https
      OAUTHLIB_INSECURE_TRANSPORT: "1"
      MONGO_URI: mongodb://mongo:27017

volumes:
  data:
    driver: local
