version: '3.4'
services:
  ####################
  # Backing services #
  ####################
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  ################
  # Our services #
  ################
  app:
    build:
      context: .
    image: nypaddlingproject
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      # Mount our local codebase over the codebase baked into the image.
      # Restarting the container will run your local code, no need to rebuild.
      - ./pyserver/server.py:/app/server.py
      - ./web/vue.js/dist:/app/dist
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      PORT: 8080
      API_URL: "localhost:8080"
      BASE_URL: "localhost:8080"
      DIST_PATH: "./dist"

volumes:
  data:
    driver: local
