version: '3.4'
services:
  ####################
  # Backing services #
  ####################
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  ################
  # Our services #
  ################
  app:
    build:
      context: .
      target: build-server
    image: nypaddlingproject
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongo
    volumes:
      # Mount our local codebase over the codebase baked into the image.
      # Restarting the container will run your local code, no need to rebuild.
      - ./pyserver/server.py:/app/server.py
      - ./web/vue.js/dist:/app/dist
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    environment:
      FLASK_DEBUG: 1
      BASE_URL: "https://nypaddledev.com"
      APP_PROTOCOL: "https"

volumes:
  data:
    driver: local
