version: '3.4'
services:
  ####################
  # Backing services #
  ####################
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  ################
  # Our services #
  ################

  app:
    build:
      context: .
    image: starter-builder
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      # Mount our local codebase over the codebase baked into the image.
      # Restarting the container will run your local code, no need to rebuild.
      - .:/starter
    command: ["go", "run", "cmd/starter/starter.go", "--debug"]

volumes:
  data:
    driver: local
